"""Generate the ESP32 deployment profile from measured calibration data."""

import argparse
import csv
import math
from itertools import pairwise
from pathlib import Path


def inverse_response(rows):
    """Invert measured drive/light pairs; reject missing, flat, or reversed data."""
    inverse = []
    for channel in ("r", "g", "b"):
        points = sorted(
            (int(row["drive"]), float(row["light"]))
            for row in rows
            if row["channel"] == channel
        )
        if len(points) < 17 or points[0][0] != 0 or points[-1][0] != 255:
            raise ValueError(
                f"{channel}: need at least 17 measured points covering drive 0 to 255"
            )
        if any(not math.isfinite(v) for _, v in points) or any(
            b[0] <= a[0] or b[1] <= a[1] for a, b in pairwise(points)
        ):
            raise ValueError(
                f"{channel}: drive and measured light must increase strictly"
            )
        black, full = points[0][1], points[-1][1]
        normalized = [
            (drive / 255, (light - black) / (full - black)) for drive, light in points
        ]
        values = []
        for i in range(17):
            desired = i / 16
            a, b = next(
                (a, b) for a, b in pairwise(normalized) if a[1] <= desired <= b[1]
            )
            values.append(a[0] + (desired - a[1]) * (b[0] - a[0]) / (b[1] - a[1]))
        inverse.append(values)
    return inverse


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--led-csv",
        type=Path,
        help="CSV: channel (r/g/b), drive (0..255), light (measured luminance)",
    )
    parser.add_argument("--white-balance", type=float, nargs=3, default=[1, 1, 1])
    parser.add_argument("--pascals-per-unit", type=float)
    parser.add_argument(
        "--input-settings",
        help="microphone ID, wiring, bit format, channel and fixed gain used for calibration",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if not args.led_csv and args.pascals_per_unit is None:
        parser.error("supply measured LED data or microphone calibration")
    if any(not math.isfinite(v) or not 0 < v <= 1 for v in args.white_balance):
        parser.error("white balance entries must be finite in (0, 1]")
    if args.pascals_per_unit is not None and (
        not math.isfinite(args.pascals_per_unit)
        or args.pascals_per_unit <= 0
        or not args.input_settings
    ):
        parser.error(
            "microphone calibration needs positive finite Pa/unit and --input-settings"
        )
    audio = (
        "Ok(Calibration::default())"
        if args.pascals_per_unit is None
        else f"Ok(Calibration::measured({args.pascals_per_unit:.9e})?)"
    )
    led = "Ok(LedResponse::default())"
    if args.led_csv:
        with args.led_csv.open(newline="") as source:
            curves = inverse_response(list(csv.DictReader(source)))
        rows = ",\n".join(
            "[" + ", ".join(f"{v:.9f}" for v in row) + "]" for row in curves
        )
        balance = ", ".join(f"{v:.9f}" for v in args.white_balance)
        led = f'LedResponse::measured([{rows}], [{balance}]).ok_or_else(|| eyre::eyre!("invalid LED profile"))'
    settings = (
        (args.input_settings or "Uncalibrated microphone")
        .replace("\n", " ")
        .replace("\r", " ")
    )
    result = f"""//! Measured deployment profile generated by validation/lights/profile.py.
//! Input: {settings}
use musical_lights_core::{{audio::loudness::Calibration, lights::LedResponse}};
pub fn input_calibration() -> eyre::Result<Calibration> {{ {audio} }}
pub fn led_response() -> eyre::Result<LedResponse> {{ {led} }}
"""
    args.output.write_text(result)


if __name__ == "__main__":
    main()
