[workspace]

resolver = "2"

members = ["musical-lights-core"]

exclude = [
    "musical-adafruit-sparkle-embassy",
    "musical-adafruit-sparkle-idf",
    "musical-feather-m0",
    "musical-leptos",
    "musical-stm32",
    "musical-terminal",
    "musical-wasm",
]
