[workspace]
members = ["musical-lights-core"]
exclude = [
    "musical-adafruit-sparkle-embassy",
    "musical-adafruit-sparkle-idf",
    "musical-dioxus",
    "musical-feather-m0",
    "musical-leptos",
    "musical-stm32",
    "musical-terminal",
    "musical-wasm",
]
resolver = "2"

# [patch.crates-io.biquad]
# git = "https://github.com/korken89/biquad-rs"
# rev = "34ee4986e7f8426e91112e4171e2a8bfbd7262c7"

# [patch.crates-io.embassy-time]
# git = "https://github.com/embassy-rs/embassy.git"
# rev = "6186d111a5c150946ee5b7e9e68d987a38c1a463"

# [patch.crates-io.embedded-hal]
# git = "https://github.com/rust-embedded/embedded-hal"
# rev = "520945278942c301433c391f63a075227d9e7c84"

# [patch.crates-io.i24]
# git = "https://github.com/jmg049/i24.git"
# rev = "50cf8bfa5d1a357de3b2d09400a018fdeec6370c"
