[workspace]

resolver = "2"

members = [
    "musical-lights-core",
]

exclude = [
    "musical-feather-m0",
    "musical-leptos",
    "musical-leptos-0",
    "musical-stm32",
    "musical-terminal",
]
