[package]
name = "musical_terminal"
version = "0.1.0"
edition = "2024"
default-run = "filter_bank"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1.0.104"
cpal = "=0.18.2"
critical-section = { version = "=1.2.0", features = ["std"] }
embassy-executor = { version = "=0.10.0", features = [
    "platform-std",
    "executor-thread",
    "log",
] }
embassy-sync = { version = "=0.8.0", features = ["log", "std"] }
embassy-time = { version = "=0.5.1", features = ["log", "std"] }
embedded-graphics = { version = "=0.8.2", features = [
    "nalgebra_support",
    "defmt",
] }
embedded-graphics-simulator = "=0.8.0"
env_logger = "=0.11.11"
flume = "=0.12.0"
log = { version = "=0.4.34", features = ["std"] }
musical-lights-core = { path = "../musical-lights-core", features = [
    "std",
    "log",
] }
smart-leds-matrix = "=0.2.0"
static_cell = { version = "=2.1.1", features = ["nightly"] }
