[package]
name = "musical-leptos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musical-lights-core = { path = "../musical-lights-core" }

console_error_panic_hook = "0.1.7"
console_log = "1"
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
log = "0.4"

[profile.release]
codegen-units = 1
lto = true
