[package]
name = "musical-leptos"
version = "0.1.0"
edition = "2021"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musical-lights-core = { path = "../musical-lights-core", features=["log"] }

leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_meta = { version = "0.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.6", features = ["csr", "nightly"] }
console_log = "1"
cpal = { version = "0.15", features = ["wasm-bindgen"] }
flume = "0.11.0"
log = "0.4"
console_error_panic_hook = "0.1"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ["console", "AudioContext", "Document", "MediaDevices", "MediaStream", "MediaStreamConstraints", "Navigator", "Window"] }

# utils
# strum = { version = "0.25", features = ["derive", "strum_macros"] }
# strum_macros = "0.25"


[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
