[package]
name = "musical-lights-core"
version = "0.1.0"
edition = "2021"

[dependencies]
circular-buffer = { version = "0.1.6", default-features = false }
embassy-sync = { version = "*" }
log = "0.4.20"
microfft = { version = "0.5.1", default-features = false, features = ["size-2048"]}
micromath = "2.1.0"
num-complex = { version = "*", default-features = false }

# # TODO:
# apodize = "1.0.0"
# flume = { version = "0.11.0", default-features = false, features = ["async"] }
# cichlid = { version = "0.2.1", features = ["no-std"] }

[features]
default = []
std = ["microfft/std", "num-complex/std"]
