[package]
name = "musical-lights-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apodize = "1.0.0"
blake2 = { version = "0.10.6", default-features = false }
cichlid = { version = "0.2.1", features = ["no-std"] }
circular-buffer = { version = "0.1.6", default-features = false }
microfft = { version = "0.5.1" }
micromath = "2.1.0"
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.51", default-features = false }
toml = "0.8.8"
