[package]
name = "musical-lights-core"
version = "0.1.0"
edition = "2021"

[dependencies]
circular-buffer = { version = "0.1.6", default-features = false }
defmt = { version = "0.3.5", default-features = false }
embedded-graphics = { version = "0.8.1" }
log = { version = "*", default-features = false, optional = true }
microfft = { version = "0.5.1", default-features = false, features = ["size-2048"]}
micromath = "2.1.0"
num-complex = { version = "0.4.4", default-features = false }
smart-leds = "0.3.0"
smart-leds-matrix = "0.1.0"

# # TODO:
# cichlid = { version = "0.2.1", features = ["no-std"] }

[features]

# TODO: defmt should be optional. both defmt and log should be additive!

default = []
std = ["microfft/std", "num-complex/std", "log/std"]
