[package]
name = "musical-lights-core"
version = "1.0.0"
edition = "2021"

[dependencies]
circular-buffer = { version = "0.1.7", default-features = false }
defmt = { version = "0.3.6", default-features = false, optional = true }
enterpolation = { version = "0.2.1", default-features = false, features = ["bspline"] }
log = { version = "*", default-features = false, optional = true }
microfft = { version = "0.5.1", default-features = false, features = ["size-2048"] }
micromath = "2.1.0"
num-complex = { version = "0.4.5", default-features = false }
palette = { version = "0.7.5", default-features = false }
smart-leds = "0.4.0"

# # TODO: use these?
# embedded-graphics = "0.8.1"
# embedded-graphics-framebuf = "0.5.0"
# cichlid = { version = "0.2.1", features = ["no-std"] }

[dev-dependencies]
test-log = "0.2.15"

[patch.crates-io]
# smart-leds-matrix = { git = "https://github.com/WyseNynja/smart-leds-matrix.git", rev = "bc4188d311498c9396afc9c798ce42171c009ab1" }
ws2812-async = { git = "https://github.com/WyseNynja/ws2812-async.git", rev = "9d2a3aa7fa800722e45ad2658feb0e39a6039f80" }

[features]

# TODO: defmt should be optional. both defmt and log should be additive!

default = ["libm", "defmt"]
defmt = ["dep:defmt"]
libm = ["palette/libm", "enterpolation/libm", "num-complex/libm"]
std = ["log?/std", "microfft/std", "num-complex/std", "palette/std", "enterpolation/std"]
