[package]
name = "musical-lights-worklet"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
musical-lights-core = { path = "../musical-lights-core", default-features = false, features = ["libm"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
