[package]
name = "musical-stm32"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
description = "Musical Lights for STM32"
repository = "https://github.com/WyseNynja/musical-lights-rs"
readme = "README.md"
edition = "2021"
resolver = "2"

[dependencies]
embassy-stm32 = { version = "0.1.0", path = "../../embassy-stm32", features = [ "defmt", "stm32f303vc", "unstable-pac", "memory-x", "time-driver-any", "exti"]  }
embassy-sync = { version = "0.5.0", path = "../../embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.4.0", path = "../../embassy-executor", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { version = "0.2", path = "../../embassy-time", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb = { version = "0.1.0", path = "../../embassy-usb", features = ["defmt"] }
embassy-futures = { version = "0.1.0", path = "../../embassy-futures" }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }

panic-probe = { version = "0.3", features = ["print-defmt"] }

# TODO: enable this once a basic blinking light program will compile
# musical-lights-core = { path = "../musical-lights-core" }

[features]
default = ["dep:panic-halt"]
use_semihosting = ["dep:panic-semihosting"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"
