[package]
name = "musical-stm32"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
description = "Musical Lights for STM32"
repository = "https://github.com/WyseNynja/musical-lights-rs"
readme = "README.md"
edition = "2021"
resolver = "2"

[dependencies]
circular-buffer = { version = "0.1.6", default-features = false }
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.3"
defmt = "0.3"
defmt-rtt = "0.4"
embassy-executor = { version = "0.4.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers", "nightly"] }
embassy-stm32 = { version = "0.1.0", features = ["defmt", "stm32f411ce", "unstable-pac", "memory-x", "time-driver-any", "exti"]  }
embassy-sync = { version = "0.5.0", features = ["defmt"] }
embassy-time = { version = "0.2", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
micromath = "2.1.0"
musical-lights-core = { path = "../musical-lights-core" }
panic-probe = { version = "0.3", features = ["print-defmt"] }
ws2812-spi = "0.4.0"

#embassy-futures = { version = "0.1.1" }
#embassy-usb = { version = "0.1.0", features = ["defmt"] }

[features]

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }

#embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }
#embassy-usb = { git = "https://github.com/embassy-rs/embassy.git", rev = "e8a832e17715c34377f5dfbe32f8a66ac1c22b45" }

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

# timings on neopixels are very sensitive
opt-level = 3

[profile.release]
debug = true
lto = true

# # TODO: optimisize for size when compiling?
# opt-level = "s"

# timings on neopixels are very sensitive
opt-level = 3
